version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
      - redis
    links:
      - db:db
    command: uvicorn mysite.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/mysite/planilla/
      - ./planilla/media:/usr/src/mysite/planilla/media  # Persistir imágenes
      - static_volume:/usr/src/mysite/planilla/static  # Montar volumen para archivos estáticos
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - mynetwork
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - mynetwork
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
volumes:
  postgres_data:
  static_volume:
  
networks:
  mynetwork:
    driver: bridge