# Generated by Django 5.1.1 on 2024-10-17 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuartel', models.CharField(max_length=2000, verbose_name='Cuartel')),
            ],
            options={
                'verbose_name': 'Cuartel',
                'verbose_name_plural': 'Cuarteles',
            },
        ),
        migrations.CreateModel(
            name='Estado_Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de los móviles',
                'verbose_name_plural': 'Estados de los móviles',
            },
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.CharField(max_length=100, verbose_name='Jerarquía')),
            ],
            options={
                'verbose_name': 'Jerarquía',
                'verbose_name_plural': 'Jerarquías',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de móvil',
                'verbose_name_plural': 'Tipos de móvil',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
            },
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('chofer', models.BooleanField(default=False)),
                ('posicion', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('IDBase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='Base')),
                ('IDJerarquia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.jerarquia', verbose_name='Jerarquía')),
            ],
            options={
                'verbose_name': 'Bombero',
                'verbose_name_plural': 'Bomberos',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('litros', models.IntegerField()),
                ('intervenciones', models.IntegerField(blank=True, null=True)),
                ('ultima_carga', models.DateTimeField(blank=True)),
                ('IDBase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='Base')),
                ('IDEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.estado_movil', verbose_name='Estado')),
                ('IDTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipo_movil')),
            ],
            options={
                'verbose_name': 'Móvil',
                'verbose_name_plural': 'Móviles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('salida', models.DateTimeField(blank=True, null=True, verbose_name='Horario de salida')),
                ('regreso', models.DateTimeField(blank=True, null=True, verbose_name='Horario de regreso')),
                ('IDMovil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil', verbose_name='Móvil')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='Encargado')),
                ('IDTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipo_servicio', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
