# Generated by Django 5.1.1 on 2024-10-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='encargado',
            new_name='IDEncargado',
        ),
    ]
