# Generated by Django 5.1.2 on 2024-10-17 19:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_rename_encargado_servicio_idencargado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bombero',
            old_name='chofer',
            new_name='es_chofer',
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('guardia', models.CharField(max_length=10)),
                ('cuartelero', models.CharField(blank=True, max_length=100, null=True)),
                ('recibido', models.IntegerField(blank=True, null=True)),
                ('gastado', models.IntegerField(blank=True, null=True)),
                ('entregado', models.IntegerField(blank=True, null=True)),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
                ('presentes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Presentes'), size=None)),
                ('ausentes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Ausentes'), size=None)),
                ('refuerzos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Refuerzos'), size=None)),
                ('servicios', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Servicios'), size=None)),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas realizadas')),
                ('novedades', models.TextField(blank=True, null=True, verbose_name='Novedades')),
                ('ayudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayudante', to='planilla.bombero', verbose_name='Ayudante')),
                ('cabecera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.compania', verbose_name='Cabecera de compañia')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer', to='planilla.bombero', verbose_name='Chofer')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado', to='planilla.bombero', verbose_name='Encargado de guardia')),
                ('oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='Oficial de semana')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='IDPlanilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.planilla', verbose_name='Planilla'),
        ),
    ]
