# Generated by Django 5.1.2 on 2024-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_rename_chofer_bombero_es_chofer_planilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='guardia',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
