# Generated by Django 5.1.2 on 2024-10-19 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_alter_planilla_fecha_alter_planilla_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='guardia_operativa',
            field=models.IntegerField(default=0, unique=True, verbose_name='Guardia operativa'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='guardia_operativa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='ausentes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Ausentes'), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='presentes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Presentes'), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='refuerzos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Refuerzos'), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='servicios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Servicios'), default=[], size=None),
        ),
    ]
