# Generated by Django 5.1.2 on 2024-10-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_remove_planilla_servicios_remove_servicio_idplanilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='presentes',
        ),
        migrations.CreateModel(
            name='GuardiaPresentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia_op', models.IntegerField()),
                ('bombero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
            },
        ),
        migrations.AddField(
            model_name='planilla',
            name='presente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.guardiapresentes', verbose_name='Presentes'),
        ),
    ]
