# Generated by Django 5.1.2 on 2024-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0007_remove_planilla_presentes_guardiapresentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='presente',
        ),
        migrations.AddField(
            model_name='planilla',
            name='presente',
            field=models.ManyToManyField(blank=True, null=True, to='planilla.guardiapresentes', verbose_name='Presentes'),
        ),
    ]
