# Generated by Django 5.1.2 on 2024-10-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0008_remove_planilla_presente_planilla_presente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='ausentes',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='presente',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='refuerzos',
        ),
        migrations.AlterField(
            model_name='guardiapresentes',
            name='guardia_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardia_op', to='planilla.planilla'),
        ),
    ]
