# Generated by Django 5.1.2 on 2024-10-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0009_remove_planilla_ausentes_remove_planilla_presente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiapresentes',
            name='guardia_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardia_presentes', to='planilla.planilla'),
        ),
        migrations.CreateModel(
            name='GuardiaAusentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('guardia_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardia_ausentes', to='planilla.planilla')),
            ],
            options={
                'verbose_name': 'Ausente',
                'verbose_name_plural': 'Ausentes',
            },
        ),
        migrations.CreateModel(
            name='GuardiaRefuerzos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('guardia_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardia_refuerzos', to='planilla.planilla')),
            ],
            options={
                'verbose_name': 'Refuerzo',
                'verbose_name_plural': 'Refuerzos',
            },
        ),
    ]
