# Generated by Django 5.1.2 on 2024-10-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0010_alter_guardiapresentes_guardia_op_guardiaausentes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado_Movil',
            new_name='EstadoMovil',
        ),
        migrations.RenameModel(
            old_name='Tipo_Movil',
            new_name='TipoMovil',
        ),
        migrations.RenameModel(
            old_name='Tipo_Servicio',
            new_name='TipoServicio',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='IDEncargado',
            new_name='encargado',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='IDMovil',
            new_name='movil',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='IDTipo',
            new_name='tipo',
        ),
    ]
