# Generated by Django 5.1.2 on 2025-01-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0011_rename_estado_movil_estadomovil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='ayudante',
        ),
        migrations.AddField(
            model_name='guardiapresentes',
            name='ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='ingreso'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='cuartel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='cuartel'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='ingreso_chofer',
            field=models.TimeField(blank=True, null=True, verbose_name='ingreso chofer'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='ingreso_encargado',
            field=models.TimeField(blank=True, null=True, verbose_name='ingreso encargado'),
        ),
    ]
