# Generated by Django 5.1.2 on 2025-01-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0012_remove_planilla_ayudante_guardiapresentes_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movil',
            name='ultima_carga',
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil')),
            ],
        ),
        migrations.CreateModel(
            name='Fluidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('agua', models.IntegerField(blank=True, null=True)),
                ('aceite', models.IntegerField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil')),
            ],
        ),
    ]
