# Generated by Django 5.1.2 on 2025-01-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0013_remove_movil_ultima_carga_combustible_fluidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidos',
            name='frenos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluidos',
            name='hidraulico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluidos',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
