# Generated by Django 5.1.2 on 2025-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0014_fluidos_frenos_fluidos_hidraulico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='ultima_carga',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
