# Generated by Django 5.1.2 on 2025-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0015_movil_ultima_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='ultima_fluidos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
