# Generated by Django 5.1.2 on 2025-01-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0016_movil_ultima_fluidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustible',
            options={'verbose_name': 'Carga de combustible', 'verbose_name_plural': 'Carga de combustible'},
        ),
        migrations.AlterModelOptions(
            name='fluidos',
            options={'verbose_name': 'Fluidos', 'verbose_name_plural': 'Fluidos'},
        ),
    ]
