# Generated by Django 5.1.2 on 2025-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0017_alter_combustible_options_alter_fluidos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movil',
            name='ultima_carga',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
