# Generated by Django 5.1.2 on 2025-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0018_alter_movil_ultima_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiapresentes',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='ingreso'),
        ),
    ]
