# Generated by Django 5.1.2 on 2025-01-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0019_guardiapresentes_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='cuartel',
        ),
    ]
