# Generated by Django 5.1.2 on 2025-01-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0020_remove_planilla_cuartel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='cuartel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='cuartel'),
        ),
    ]
