# Generated by Django 5.1.2 on 2025-01-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0021_planilla_cuartel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planilla',
            old_name='cuartel',
            new_name='cuartel_id',
        ),
    ]
