# Generated by Django 5.1.2 on 2025-01-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0022_rename_cuartel_planilla_cuartel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planilla',
            old_name='cuartel_id',
            new_name='cuartel',
        ),
    ]
