# Generated by Django 5.1.2 on 2025-01-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0023_rename_cuartel_id_planilla_cuartel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidos',
            name='bomba',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fluidos',
            name='luces',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fluidos',
            name='sirena',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fluidos',
            name='tanque',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
