# Generated by Django 5.1.2 on 2025-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0024_fluidos_bomba_fluidos_luces_fluidos_sirena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluidos',
            name='bomba',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fluidos',
            name='luces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fluidos',
            name='sirena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fluidos',
            name='tanque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
