# Generated by Django 5.1.2 on 2025-01-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0025_alter_fluidos_bomba_alter_fluidos_luces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='Base')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('cantidad', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número')),
                ('salida', models.DateTimeField(blank=True, null=True, verbose_name='Horario de salida')),
                ('regreso', models.DateTimeField(blank=True, null=True, verbose_name='Horario de regreso')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='Encargado')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil', verbose_name='Móvil')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tiposervicio', verbose_name='Tipo de servicio')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.ubicacion', verbose_name='ubicacion')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
