# Generated by Django 5.1.2 on 2025-01-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0026_ubicacion_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoMovil',
            new_name='Estado',
        ),
        migrations.RemoveField(
            model_name='material',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='material',
            name='regreso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='salida',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tipo',
        ),
        migrations.AddField(
            model_name='material',
            name='cajonera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.estado', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ubicacion'),
        ),
    ]
