# Generated by Django 5.1.2 on 2025-01-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0027_rename_estadomovil_estado_remove_material_encargado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
