# Generated by Django 5.1.2 on 2025-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0028_alter_estado_options_alter_material_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
