# Generated by Django 5.1.2 on 2025-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0030_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materiales/'),
        ),
    ]
