# Generated by Django 5.1.2 on 2025-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0031_alter_material_cantidad_alter_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
    ]
