# Generated by Django 5.1.2 on 2025-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0032_alter_material_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='ubicacion')),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
