# Generated by Django 5.1.2 on 2025-01-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0033_tipomaterial_material_potencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo de motor')),
            ],
            options={
                'verbose_name': 'Tipo de motor',
                'verbose_name_plural': 'Tipos de motores',
            },
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tipo de material'),
        ),
    ]
