# Generated by Django 5.1.2 on 2025-01-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0034_tipomotor_alter_tipomaterial_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipomotor', verbose_name='tipo de motor'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipomaterial', verbose_name='tipo de material'),
        ),
    ]
