# Generated by Django 5.1.2 on 2025-01-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0035_material_motor_material_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomaterial',
            options={'verbose_name': 'Tipo de material', 'verbose_name_plural': 'Tipos de materiales'},
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='tipo de material')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='encargado')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.estado', verbose_name='estado')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
            },
        ),
    ]
