# Generated by Django 5.1.2 on 2025-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0036_alter_tipomaterial_options_cambioestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestado',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de cambio'),
        ),
    ]
