# Generated by Django 5.1.2 on 2025-01-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0037_cambioestado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='motivo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='tipo de material'),
        ),
    ]
