# Generated by Django 5.1.2 on 2025-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0038_alter_cambioestado_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estado'),
        ),
    ]
