# Generated by Django 5.1.2 on 2025-01-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0039_servicio_direccion_servicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='latitud',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='longitud',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='longitud'),
        ),
    ]
