# Generated by Django 5.1.2 on 2025-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0040_servicio_latitud_servicio_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiapresentes',
            name='encargado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='encargado'),
        ),
    ]
