# Generated by Django 5.1.2 on 2025-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0041_guardiapresentes_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiapresentes',
            name='chofer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='chofer'),
        ),
    ]
