# Generated by Django 5.1.2 on 2025-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0042_guardiapresentes_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(blank=True, max_length=140, null=True, verbose_name='nombre')),
                ('tipo', models.CharField(blank=True, choices=[('Policia', 'Policia'), ('Bomberos', 'Bomberos'), ('Ambulancia', 'Ambulancia'), ('Defensa Civil', 'Defensa Civil'), ('Otros', 'Otros')], max_length=120, null=True, verbose_name='tipo')),
                ('descripcion', models.CharField(blank=True, max_length=140, null=True, verbose_name='descripcion')),
                ('direccion', models.CharField(blank=True, max_length=140, null=True, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('telefono2', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono 2')),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
