# Generated by Django 5.1.2 on 2025-01-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0043_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cubriendo zona', 'Cubriendo zona'), ('En apoyo', 'En apoyo'), ('Sin chofer', 'Sin chofer')], max_length=20, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='direccion',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='frecuencia'),
        ),
    ]
