# Generated by Django 5.1.2 on 2025-01-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0044_base_estado_alter_agenda_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReparacionMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.CharField(blank=True, max_length=50, null=True, verbose_name='tarea')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('movil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil')),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
            },
        ),
    ]
