# Generated by Django 5.1.6 on 2025-02-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0045_reparacionmovil'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='zona',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cubriendo zona', 'Cubriendo zona'), ('En apoyo', 'En apoyo'), ('Sin chofer', 'Sin chofer')], default='Cubriendo zona', max_length=20, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='movil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil', verbose_name='móvil'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipomaterial', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='IDBase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.base', verbose_name='base'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='IDEstado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.estado', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='IDTipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tipomovil', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='intervenciones',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movil',
            name='litros',
            field=models.IntegerField(blank=True, null=True, verbose_name='litros de combustible'),
        ),
        migrations.AlterField(
            model_name='movil',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='tipo de servicio'),
        ),
        migrations.CreateModel(
            name='ServicioPresentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.servicio')),
            ],
            options={
                'verbose_name': 'Presente en servicio',
                'verbose_name_plural': 'Presentes en servicio',
            },
        ),
    ]
