# Generated by Django 5.1.6 on 2025-02-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0046_servicio_zona_alter_base_estado_alter_material_movil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre_denunciante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='denunciante'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='telefono_denunciante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='ncargado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='guardia_operativa',
            field=models.IntegerField(blank=True, null=True, verbose_name='guardia operativa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='movil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.movil', verbose_name='móvil'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='regreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de regreso'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de salida'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.tiposervicio', verbose_name='tipo de servicio'),
        ),
    ]
