# Generated by Django 5.1.6 on 2025-02-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0047_servicio_nombre_denunciante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomberos', models.ManyToManyField(blank=True, to='planilla.bombero')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.movil')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviles_asignados', to='planilla.servicio')),
            ],
            options={
                'verbose_name': 'Presente en servicio',
                'verbose_name_plural': 'Presentes en servicio',
            },
        ),
        migrations.DeleteModel(
            name='ServicioPresentes',
        ),
    ]
