# Generated by Django 5.1.6 on 2025-02-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0048_serviciomovil_delete_serviciopresentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='movil',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='planilla.tiposervicio', verbose_name='tipo de servicio'),
        ),
    ]
