# Generated by Django 5.1.2 on 2025-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0049_remove_servicio_movil_alter_servicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidos',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
