# Generated by Django 5.1.2 on 2025-02-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0050_fluidos_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('día', 'Día'), ('noche', 'Noche')], max_length=10)),
                ('ayudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_ayudante', to='planilla.bombero')),
                ('bomberos', models.ManyToManyField(related_name='guardias_bomberos', to='planilla.bombero')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_chofer', to='planilla.bombero')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_encargado', to='planilla.bombero')),
            ],
            options={
                'unique_together': {('fecha', 'turno')},
            },
        ),
    ]
