# Generated by Django 5.1.2 on 2025-02-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0051_guardia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardia',
        ),
    ]
