# Generated by Django 5.1 on 2025-04-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0052_delete_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestado',
            name='guardia_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.planilla', verbose_name='Guardia operativa'),
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer_movil', to='planilla.bombero'),
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_movil', to='planilla.bombero'),
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de salida'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.bombero', verbose_name='encargado'),
        ),
    ]
