# Generated by Django 5.1 on 2025-04-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0053_cambioestado_guardia_operativa_serviciomovil_chofer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciomovil',
            old_name='encargado',
            new_name='encargado_movil',
        ),
        migrations.RenameField(
            model_name='serviciomovil',
            old_name='salida',
            new_name='salida_movil',
        ),
    ]
