# Generated by Django 5.1 on 2025-04-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0054_rename_encargado_serviciomovil_encargado_movil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciomovil',
            name='encargado_movil',
        ),
        migrations.RemoveField(
            model_name='serviciomovil',
            name='salida_movil',
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_movil', to='planilla.bombero'),
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de salida'),
        ),
    ]
