# Generated by Django 5.1 on 2025-04-29 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0055_remove_serviciomovil_encargado_movil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciomovil',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='serviciomovil',
            name='salida',
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='encargado_movil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_movil', to='planilla.bombero'),
        ),
        migrations.AddField(
            model_name='serviciomovil',
            name='salida_movil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='horario de salida'),
        ),
        migrations.CreateModel(
            name='ServicioMovilEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_camino', 'En camino'), ('en_escena', 'En escena'), ('de_regreso', 'De regreso')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('servicio_movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='planilla.serviciomovil')),
            ],
        ),
    ]
