# Generated by Django 5.1 on 2025-04-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0056_remove_serviciomovil_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomovilevento',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planilla.estado', verbose_name='estado'),
        ),
    ]
