# Generated by Django 5.1 on 2025-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0057_alter_serviciomovilevento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='celular',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
