# Generated by Django 5.1 on 2025-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0058_bombero_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombero',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
